{{- if .Values.apps.aiwa-app.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiwa-app
  namespace: default
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.apps.aiwa-app.path }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}